[package]
name = "mod_logger"
version = "0.1.0"
authors = ["Thomas <thomas@etnur.net>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/test.rs"


[dependencies]
log = { version = "^0.4.5", features = ["std"] }
chrono = "0.4.6"
stderrlog = "*"
yaml-rust = "0.4"
colored = "1.7"
regex = "1"
failure = "*"
